name: Publish to NuGet

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      MAJOR_MINOR: "0.2"
      NUGET_SOURCE: "https://api.nuget.org/v3/index.json"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Calculate Version
        id: version
        run: |
          VERSION="${{ env.MAJOR_MINOR }}.${{ github.run_number }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building Version: $VERSION"

      - name: Pack MonoEight.Templates
        run: |
          dotnet pack MonoEight.Templates/MonoEight.Templates.csproj \
            --configuration Release \
            -p:Version=${{ steps.version.outputs.version }} \
            --output ./nupkgs

      - name: Push MonoEight.Templates
        run: |
          dotnet nuget push ./nupkgs/MonoEight.Templates.${{ steps.version.outputs.version }}.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source ${{ env.NUGET_SOURCE }} \
            --skip-duplicate